kind: pipeline
name: default

steps:

  - name: test python
    image: python:3.7
    commands:
      - pip install pytest black
      - make python
    depends_on:
      - clone

  - name: test rust
    image: rust:1.34
    commands:
      - make rust
    depends_on:
      - clone

  - name: test golang
    image: golang:1.12
    commands:
      - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - make go
    depends_on:
      - clone

  - name: test elisp
    image: flycheck/emacs-cask:26.3
    commands:
      - make elisp
    depends_on:
      - clone
